name: 'Deploy to Firebase Functions with Node 18'
author: 'Jakob Becker <LikeAnOwner@gmail.com>'
description: 'A GitHub Action to deploy to Firebase Functions with Node Version 18'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'red'
